### ISSUE TITLE
find all contours ValueError: need more than 2 values to unpack

### ISSUE THREAD

**Issue by Bilalsaghir** [MicrocontrollersAndMore/OpenCV_3_KNN_Character_Recognition_Python#14]
I am getting this error. anyone, please help.

C:\Python27\python.exe "C:/Users/Entrepreneur/Documents/Python Scripts/numberplate/Main.py"
Traceback (most recent call last):
  File "C:/Users/Entrepreneur/Documents/Python Scripts/numberplate/Main.py", line 134, in <module>
    main()
  File "C:/Users/Entrepreneur/Documents/Python Scripts/numberplate/Main.py", line 38, in main
    listOfPossiblePlates = DetectPlates.detectPlatesInScene(imgOriginalScene)           # detect plates
  File "C:\Users\Entrepreneur\Documents\Python Scripts\numberplate\DetectPlates.py", line 43, in detectPlatesInScene
    listOfPossibleCharsInScene = findPossibleCharsInScene(imgThreshScene)
  File "C:\Users\Entrepreneur\Documents\Python Scripts\numberplate\DetectPlates.py", line 133, in findPossibleCharsInScene
    imgContours, contours, npaHierarchy = cv2.findContours(imgThreshCopy, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)   # find all contours
ValueError: need more than 2 values to unpack

Process finished with exit code 1

**Comment by chia56028** [comment]
Just change this:
imgContours, contours, npaHierarchy = cv2.findContours(imgThreshCopy, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
To this:
contours, npaHierarchy = cv2.findContours(imgThreshCopy, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
